### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
# імпорт бібліотек

import numpy as np

In [3]:
# функція виводу масиву та розмірності

def print_array_shape(arr):

    print(arr)
    print(f"\nРозмірність {arr.shape}")

In [19]:
# вектор

vector = np.array(np.random.uniform(0, 1, 10))
print_array_shape(vector)

[0.23529418 0.49500852 0.64962982 0.80563481 0.55692382 0.0594684
 0.51454798 0.4677703  0.39721482 0.51783914]

Розмірність (10,)


In [5]:
# матриця

matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
print_array_shape(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмірність (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
# task 2.1

vector = np.round(vector+10, 2)
print(vector)

[10.31 10.15 10.   10.84 10.09 10.36 10.34 10.16 10.22 10.89]


In [7]:
# task 2.2

matrix = matrix * 2
print(matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [8]:
#task 2.3

vector2 = np.multiply(vector, vector)
print(vector2)

[106.2961 103.0225 100.     117.5056 101.8081 107.3296 106.9156 103.2256
 104.4484 118.5921]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [17]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)


array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

(2, 1)

In [10]:
#task 3.1

result_matrix = np.dot(B,A)
print_array_shape(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]

Розмірність (2, 2)


In [11]:
# task 3.2

res2 = np.dot(result_matrix, C)
print_array_shape(res2)

[[0.5202]
 [0.2846]]

Розмірність (2, 1)


In [12]:
# task 3.3

res3 = np.dot(result_matrix, D)
print_array_shape(res3)

[[0.5202 0.7281]
 [0.2846 0.2034]]

Розмірність (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [13]:
# task 4.1

result_matrix_tr = result_matrix.T
print_array_shape(result_matrix_tr)

[[0.7281 0.2034]
 [0.5202 0.2846]]

Розмірність (2, 2)


In [14]:
# task 4.2

vector.T
print_array_shape(vector.T)

[10.31 10.15 10.   10.84 10.09 10.36 10.34 10.16 10.22 10.89]

Розмірність (10,)


In [15]:
# task 4.3

column_vector = np.expand_dims(vector,axis = 1)
print_array_shape(column_vector)

[[10.31]
 [10.15]
 [10.  ]
 [10.84]
 [10.09]
 [10.36]
 [10.34]
 [10.16]
 [10.22]
 [10.89]]

Розмірність (10, 1)


In [16]:
#task 4.4

print_array_shape(column_vector.T)

[[10.31 10.15 10.   10.84 10.09 10.36 10.34 10.16 10.22 10.89]]

Розмірність (1, 10)


**Висновки**

Вектор vector це одномірний масив:

* ітерація відбувається за одним індексом;
* він не змінює форму при транспонуванні.

Після методу expand_dims ми отримали двумірний масив з розмірністю (10, 1):

* ітерація за двома індексами (номер рядка та стовпця);
* у разі транспонування ми отримаємо двумірний масив з розмірністю (1,10).


