### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [59]:
# імпорт бібліотек

import numpy as np

In [60]:
# функція виводу масиву та розмірності

def print_array_shape(arr):

    print(arr)
    print(f"\nРозмірність {arr.shape}")

In [61]:
# вектор

vector = np.array(np.random.uniform(0, 1, 10))
print_array_shape(vector)

[0.41565123 0.73933057 0.83066724 0.38785101 0.13083166 0.1437672
 0.62990956 0.78485341 0.83788553 0.65108349]

Розмірність (10,)


In [62]:
# матриця

matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
print_array_shape(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмірність (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [63]:
# task 2.1 

vector = np.round(vector+10, 2)
print(vector)

[10.42 10.74 10.83 10.39 10.13 10.14 10.63 10.78 10.84 10.65]


In [64]:
# task 2.2

matrix = matrix * 2
print(matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [65]:
#task 2.3

vector2 = np.multiply(vector, vector)
print(vector2)

[108.5764 115.3476 117.2889 107.9521 102.6169 102.8196 112.9969 116.2084
 117.5056 113.4225]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [68]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [71]:
#task 3.1

result_matrix = np.dot(B,A)
print_array_shape(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]

Розмірність (2, 2)


In [76]:
# task 3.2

res2 = np.dot(result_matrix, C)
print_array_shape(res2)

[[0.5202]
 [0.2846]]

Розмірність (2, 1)


In [78]:
# task 3.3

res3 = np.dot(result_matrix, D)
print_array_shape(res3)

[[0.5202 0.7281]
 [0.2846 0.2034]]

Розмірність (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [79]:
result_matrix_tr = result_matrix.T
print_array_shape(result_matrix_tr)

[[0.7281 0.2034]
 [0.5202 0.2846]]

Розмірність (2, 2)
